spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: watchlist-service
    password: watchlist-service
    url: jdbc:postgresql://postgres-watchlist:5432/watchlist
  rabbitmq:
    host: rabbitmq-server

item:
  url: http://item-service:8088

jwt:
  secret: G+KbPeShVmYq3t6w9z$C&F)J@McQfTjW
